#!/usr/bin/env php

<?php

set_time_limit(0);

$app = require_once __DIR__ .'/bootstrap.php';

$console = &$app["console"];
$console->add(new Omgcatz\Command\CreateTables());
$console->add(new Omgcatz\Command\InstallSlaves());
$console->run();
